### ISSUE TITLE
Not working with browserify

### ISSUE THREAD

**Issue by jenius** [segmentio/analytics.js#398]
I've got this error throwing:

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: module "./protos" not found from "xxx/node_modules/analytics.js/analytics.js"
  at notFound (xxx/node_modules/browserify/index.js:812:15)
  at xxx/node_modules/browserify/index.js:762:23
  at xxx/node_modules/browserify/node_modules/browser-resolve/index.js:184:24
  at xxx/node_modules/browserify/node_modules/resolve/lib/async.js:42:22
  at load (xxx/node_modules/browserify/node_modules/resolve/lib/async.js:60:43)
  at xxx/node_modules/browserify/node_modules/resolve/lib/async.js:66:22
  at xxx/node_modules/browserify/node_modules/resolve/lib/async.js:21:47
  at Object.oncomplete (fs.js:107:15)
```

Installed `analytics.js` directly through npm and required with browserify. Let me know if there's a different way I should be using it and I'm missing something! Also if there's anything I can do to help fix this, happy to give it a shot.

**Comment by vvo** [comment]
@nrako @simenbrekken @pwhisenhunt @yields So I made a module that wraps the snippet plus some minor additions so that you can use it with browserify easily.

See: https://github.com/vvo/analytics.js-loader

```shell
npm install analytics.js-loader --save
```

```js
var analytics = require('analytics.js-loader')({
  writeKey: 'YOUR_WRITE_KEY'
});

analytics.identify('1e810c197e', {
  name: 'Bill Lumbergh',
  email: 'bill@initech.com'
});

analytics.track('Signed Up', {
  plan: 'Startup',
  source: 'Analytics Academy'
});
```

**Comment by yields** [comment]
@xeoncore hey can you add `segmentio` to npm owners?

**Comment by nelix** [comment]
Any progress with this getting working correctly with browserify/webpack/etc?

**Comment by xeoncore** [comment]
@yields You already are.

**Comment by minibikini** [comment]
+1 for browserify support

**Comment by domderen** [comment]
+1

**Comment by Nijikokun** [comment]
*facepalms*

**Comment by joeellis** [comment]
+1 for browserify support

**Comment by Philmod** [comment]
+1

**Comment by justinmc** [comment]
Sorry I don't know much about the inner workings of Segment, but why does it require you to dynamically load the SDK from a custom URL?  Maybe it's not possible given how it works, but it would be great to be able to do something like this with no dynamic loading of scripts:

    var analytics = require('analytics.js');
    analytics.setKey('mykey');
    analytics.track(...);

Setting up the way that's shown in the quickstart guide seems archaic and difficult to update.  Is it a security or cross origin problem?

**Comment by thomasmodeneis** [comment]
+1 for browserify support

**Comment by seanadkinson** [comment]
+1

**Comment by mmahalwy** [comment]
No news on this so far?

**Comment by foiseworth** [comment]
@justinmc the custom url load a specific bundle for your integrations. I think I read previously that the bundle of all integrations would be 30MB+

**Comment by sperand-io** [comment]
Thanks everyone for weighing in here!

The core of analytics.js is pretty much void of value unless you're also `.use`ing some integrations with it. These integration plugins will almost always load a subsequent third party library onto the window and then proxy your analytics calls through that global object's methods. 

So it's not really a self-contained module; whether you inline just the snippet, a build with just the integrations you need, or one with *all* the integrations, it's still going to leak onto the window, which is why we've never prioritized being able to roll  it up in your app js bundles via browserify, webpack, etc.

We think that regardless of whether you're a Segment customer using the hosted, dynamically-rendered (and cached) build with only the integrations you've enabled and setup in our UI, or you're using a modified snippet that loads a [custom build of your own](https://github.com/segmentio/analytics.js/wiki/Building-a-Custom-Distribution), the snippet approach is the right way to go as it will load asynchronously and queue any calls in the meantime. 

That said, there are some learnings and admissions for us to make here. Currently, each of the segment-supported open-source integrations use Duo (née component) to pull in dependencies, meaning that if you wanted to build a piecemeal version of analytics.js for hosting on your own, you'd need to do so with Duo. Otherwise, you have to use the UMD build that includes *all* integrations. Not ideal.

We'll be porting `analytics.js-core` and `analytics.js-integration-*` to be npm / commonjs compatible so that if you choose not to use Segment, you can still easily create a custom build that is more modular with a more mainstream build tool. (We'd still recommend using a snippet to actually fetch it). Keep an eye out for that!

I'm going to close this for now, with apologies for not getting a more complete answer here sooner. If I'm missing anything — please let me know, we're happy to consider any further input!

**Comment by cristianurbano** [comment]
you can use it like this:

```shell
npm install --save analytics.js
```

```javascript
import analytics from 'analytics.js';

analytics.initialize({
    'Google Analytics': {
        trackingId: 'UA-XXXXXX-1',
    }
});
analytics.page();
