### ISSUE TITLE
anonymous_id should always be set, even if both cookies and localStorage are not enabled

### ISSUE THREAD

**Issue by jonathanong** [segmentio/analytics.js#439]
to reproduce, i ran the tests while blocking cookies in safari. i entered `analytics.user().anonymousId()` and it returns `null`.

the problem is as follows:

we have ads that run in publisher's containers (mobile apps + iframes). some, specifically twitter's mopub network, seem to disable cookies and/or localstorage (we think it's just cookies). because anonymousids are not automatically set by segment in this instance (and we don't set the userid because these are ads and are not associated with users, though we're probably going to know just to get around this issue), segment refuses to track any events (we get 400 errors in our logs saying "userid or anonymousid must be set", but no end-user-specific errors).

we tried setting our own anonymousid, but because segment loads asynchronously, we can't `.track()` before segment loads. either way, it seems like a hack. 

Q1:

is there a reason anonymous id does not just default to a "session" id when persistence is unavailable? in other words, it lasts as long as the javascript environment lasts. seems better than returning `null`. end-users wouldn't be able to do any better.

Q2:

for this specific ad problem we're having, we've tested through safari dev tools inside the container. it seems as though we can get/set data with `localStorage` directly, but not with cookies. we think it's `store.js` just returning `!store.enabled` (maybe because it relies on cookies) which sets the anonymous id as `null`. is there a reason you guys still use `store.js`?

**Comment by sperand-io** [comment]
@yields i thought we created a uid when cookies/localstorage are inaccessible. thoughts?

**Comment by yields** [comment]
> is there a reason anonymous id does not just default to a "session" id when persistence is unavailable? in other words, it lasts as long as the javascript environment lasts. seems better than returning null. end-users wouldn't be able to do any better.

yeah, the reason for me was that some website's "js" session is really short, like most websites that  have server side rendering instead of ajax/react/angular.

if we go with "js" session the flow is interrupted: `Visit home page  ->  Visit pricing  -> Signup -> Login`
each one of those steps would yield a new anonymousId, this makes sql not very useful, so i made sure that if there's some error generating the anonymousId segment integration would let you know by erroring.

> for this specific ad problem we're having, we've tested through safari dev tools inside the container. it seems as though we can get/set data with localStorage directly, but not with cookies. we think it's store.js just returning !store.enabled (maybe because it relies on cookies) which sets the anonymous id as null. is there a reason you guys still use store.js?

You might be using older version of analytics.js somehow? confused since store.js doesn't touch any cookies https://github.com/segmentio/store.js/blob/master/store.js also it doesn't have `.enabled`.

I think the best solution is to have analytics.js fallback to setting anonymousId / userId using localStorage when cookies are not available (cc @ianstormtaylor on that idea).

> we tried setting our own anonymousid, but because segment loads asynchronously, we can't .track() before segment loads. either way, it seems like a hack.

We recently added `.setAnonymousId()` in the snippet just for the situation you are in, so you can do something like:

```js
// after the snippet
localStorage.aid = localStorage.aid || generate();
analytics.setAnonymousId(localStorage.aid);
analytics.page();
analytics.track('event!');
```

^ the above calls will be called in the order they are in, so `.page()` and `.track()` will have the anonymousId you've set.

(thanks for the detailed report!)

**Comment by yields** [comment]
err actually `.setAnonymousId()` wouldn't work for you, since there are no cookies, so another solution would be:

```js
analytics.page('foo', {}, { anonymousId: localStorage.aid });
analytics.track('event', {}, { anonymousId: localStorage.aid });
// ^ or just wrap `.track()`, `.page()` etc.. to do that for you.
```

not ideal, but you can do that for now until we come up with a solution for environments that don't have cookies.

--

Another solution i just thought about is to use [analytics-node](https://github.com/segmentio/analytics-node), you can use browserify or just the [dist](https://github.com/segmentio/analytics-node/blob/master/analytics-node.js) it can be used in the browser, only con is that you have to send `anonymousId` and `.ip, .userAgent` etc...

**Comment by jonathanong** [comment]
sorry didn't read store.js's code :package: 

> I think the best solution is to have analytics.js fallback to setting anonymousId / userId using localStorage when cookies are not available

sounds good to me!

going to try the snippet above!

```
analytics.page('foo', {}, { anonymousId: localStorage.aid });
analytics.track('event', {}, { anonymousId: localStorage.aid });
// ^ or just wrap `.track()`, `.page()` etc.. to do that for you.
```

**Comment by yields** [comment]
https://github.com/segmentio/analytics.js/commit/29443b0c2363357420ee15508414d03f33d5679e

**Comment by jonathanong** [comment]
:+1:
