### ISSUE TITLE
Filter Bot Traffic

### ISSUE THREAD

**Issue by graingert** [segmentio/analytics.js#459]
We've been doing some analysis on data coming from Segment and have found that some messageId and anonymousId values are duplicated.

I suspect this is because Segment uses the uuid lib which pulls randomness from Math.random (This may not be seeded depending on implementation)

This library could use https://github.com/davidbau/seedrandom

``` javascript
var seedrandom = require('seedrandom'),
    rng = seedrandom()

function makeRandomString(length){
    // uuids are nice, but random strings are better.
    var text = "",
        possible = "0123456789abcdef-";
    for( var i=0; i < length; i++ ){
        text += possible.charAt(Math.floor(rng() * possible.length));
    }
    return text;
}
```

**Comment by graingert** [comment]
I suspect this is because it uses randomness from potentially unseeded Math.random

**Comment by sperand-io** [comment]
thanks! investigating this evening / tomorrow.

**Comment by sperand-io** [comment]
@ndhoule thoughts on this?

**Comment by sperand-io** [comment]
Hey @graingert, thanks so much for reporting this. Definitely a concern. The issue with `seedrandom` is that it alters the `Math` object, which isn't a very nice thing for us to do, because we're 3rd party.

@calvinfo @yields thoughts on how we could proceed?

**Comment by calvinfo** [comment]
Yeah we're a little hosed since there's no way to really guarantee randomness without making a specific request to seed it. That library basically tries to grab from the browser data to achieve a little bit better randomness:

 ```js
//
// autoseed()
// Returns an object for autoseeding, using window.crypto if available.
//
/** @param {Uint8Array|Navigator=} seed */
function autoseed(seed) {
  try {
    if (nodecrypto) return tostring(nodecrypto.randomBytes(width));
    global.crypto.getRandomValues(seed = new Uint8Array(width));
    return tostring(seed);
  } catch (e) {
    return [+new Date, global, (seed = global.navigator) && seed.plugins,
      global.screen, tostring(pool)];
  }
}
```

**Comment by argh** [comment]
Just found this thread because we also hit duplicate messageids.  This was more than concerning, its kind of in the "hey, uuid, you had ONE job" department, so we were kinda freaking out.

However, for our results, it appeared that the duplicate uuids were on events that were basically identical, but differed in only two things: timestamp and ip address.  Reverse resolving the ip address: googlebot.

Some more deep research (*cough* 10 second search on "googlebot random entropy") suggests that Google always generates 0.5 for random.  So.  I'm assuming that Segment has to do client-side uuid generation so that the messageids are the same across all endpoints, this would say you can't really trust client-generated messageid uniqueness based only on random() at all.

**Comment by graingert** [comment]
Segment needs to either provide randomness from their server or allow us to inject a random seed at runtime

**Comment by calvinfo** [comment]
Hey guys, did this help at all?

https://github.com/segment-integrations/analytics.js-integration-segmentio/commit/54576b3398265892a07e3b27e571a60ece104215

It also hashes the message itself so that if it's generating ones with new
timestamps, they'll be given unique ids. It *should *have taken care of any
problems you're seeing, are these recent timestamps?

We're also planning on falling back to `crypto` where it's supported, but
letting the user seed is an interesting idea.

**Comment by argh** [comment]
About half of the dups have the same timestamp but different IPs.  The other half of the dups differ only in IP.  The Googlebot issue is concerning enough that I'm certainly not going to trust UUIDs to random() in the future!

In any case, with an incrementing counter added to the event, you could guarantee that even an accidental double-purchase-within-one-ms bug would still generate two events and then appear downstream for diagnosis.

**Comment by calvinfo** [comment]
We just replicated this and confirmed it's definitely happening for googlebots (and possibly anything else with a weird `Math.random()` or stub'd `new Date()` set). We're thinking about moving the `messageId` field to be only generated on the server-side, which would fix this issue, but lose tracing end-to-end. We'll keep you posted!

**Comment by graingert** [comment]
End to end tracing is pretty handy, I'd rather go for server side seeding

**Comment by argh** [comment]
Would server-side imply you couldn't correlate say, an event in Mixpanel with something in GA without adding an additional id as a property?  Because I think we def need some sort of consistent id value across services.  Perhaps you can start transmitting events from your servers to the third party services instead of the N-way fanout suffering injected into the clients?  ;-)

**Comment by calvinfo** [comment]
Looked more at this, it looks like Googlebot fakes the timestamp, `Math.random()`, and the same call,  that's what's causing it. Since we only de-duplicate within an hourly window, the bot's events will get through if it's sent multiple times over a given day. We're thinking of how to increase that de-dupe window, making another request to get the seed is slightly annoying since it'd slow down the load time, but it's something we can do. We can't bake it into the original request since that's distributed by our CDN.

> Perhaps you can start transmitting events from your servers to the third party services instead of the N-way fanout suffering injected into the clients? ;-)

Haha, we do this on the server-side/mobile already! :D We should enable more ways for clients to choose how their data gets routed. The thought is that you could go through our servers if you don't really care about cookie-ing

**Comment by graingert** [comment]
@calvinfo bump

**Comment by calvinfo** [comment]
@graingert would filtering out bot UAs solve your issue? That should solve the core issue which is creating duplicate messageIds.

Or it the anonymousIds that are the bigger problem here?

**Comment by graingert** [comment]
Pinging @adamchainz

**Comment by adamchainz** [comment]
Hi, I'm @graingert's colleague... well ex-colleague, he's since moved on from YPlan, and using Segment.

This issue does still affect us a little and we have to account for it in some of our analyses, but as you've suggested, ignoring bot UA's is an easy way for us to do this.

**Comment by calvinfo** [comment]
Sounds good! @sperand-io can weigh in where bot detection falls, but it's an idea we've kicked around and it should be pretty easy to add https://github.com/gjohnson/is-bot

**Comment by f2prateek** [comment]
Wondering if this is still an issue, now that our dedupe window is longer (in the order of days and not hours).

**Comment by f2prateek** [comment]
Tracking internally in JIRA https://segment.atlassian.net/browse/LIB-150
