### ISSUE TITLE
analytics.track modify passed arguments

### ISSUE THREAD

**Issue by QuentinFchx** [segmentio/analytics.js#465]
I want to log an object with a `day`property.
I pass it to `analytics.track` before sending it to my server, and what happens next is completely unbelievable.

``` js
a = {day: "2015-05-28"};
analytics.track('foo', a);
a; // Object {day: Thu May 28 2015 02:00:00 GMT+0200 (CEST)}
```

... Why ? :cry: 
Why would my object be modified by a tracking library?
Do what you want with the data but please: CLONE IT before! :sob:

**Comment by vmeyet** [comment]
sad...

**Comment by QuentinFchx** [comment]
@ianstormtaylor @ndhoule, could you please advice on this ?
I'm not sure it's intended.

**Comment by f2prateek** [comment]
As a workaround you can call clone yourself before giving us the object.

**Comment by ndhoule** [comment]
@QuentinFchx this is definitely an issue, thanks for reporting. Here's the offending line of code:

https://github.com/segmentio/facade/blob/1.4.7/lib/facade.js#L25

In all other cases we clone the object before using it, but `isodate-traverse` modifies the object in place; in a previous version it cloned its input first. I'll bet that's where the issue was introduced. So the mutation issue is limited to properties that are in a date-ish format, but any mutation is not OK—totally reasonable concern.

I'll prep a fix and some regression tests for this first thing tomorrow morning when I get in.

**Comment by QuentinFchx** [comment]
Thanks a lot guys :+1:

You're completely right, the proper fix would be to clone the object in my code.
However, because I'm using it in a cordova application, it implies a new release on the different app stores (versus analytics being updated and users only having to relaunch the app :smile:)

**Comment by vmeyet** [comment]
Thanks for the answers, is there an ETA, for the release of the fix?

**Comment by ndhoule** [comment]
Sorry for taking to long to wrap this up. This was fixed in https://github.com/segmentio/facade/pull/81. 

This is up on Segment's CDN as of last night, and the built version of `analytics.js` in this repo also contains the fix.

Thanks for your patience!

**Comment by QuentinFchx** [comment]
Thank you :)
