### ISSUE TITLE
analytics.track callback is never called when lib is not loaded

### ISSUE THREAD

**Issue by nonken** [segmentio/analytics.js#474]
Scenario:

    1. Add `127.0.0.1 cdn.segment.io` to your hostsfile (simulating dead end)
    2. run `analytics.track("Event", {}, function() {})

The callback will never be called. We're now checking for analytics.options before making the call but that seems like a pretty bad workaround. 

Any feedback would really be appreciated!

**Comment by kmiyashiro** [comment]
The callback is just called after a certain timeout. One way to make sure the callback is always called is to create a wrapper around `analytics` and just re-implement the callback logic yourself.

```js
var ANALYTICS_METHODS = [
  'track',
  'alias',
  'identify',
  'page',
  'screen',
  'group'
];

var wrapper = {};

ANALYTICS_METHODS.forEach(function(method) {
  wrapper[method] = function() {
    var callback;
    [logic to detect a callback in arguments and assign to var and extract from args]
    
    analytics[method].apply(analytics, argsWithoutCallback);
    if (callback) setTimeout(callback, 250);
  }
}
```

**Comment by hankim813** [comment]
Sorry for the very VERY late reply here. But we will update docs to reflect this behavior. With that said, I think it's reasonable that this is the expected behavior since the purpose of the callback is to reasonably provide an estimate that the event was delivered. If the library doesn't load, the event won't be delivered
