### ISSUE TITLE
IE9 sends events via GET not POST

### ISSUE THREAD

**Issue by jonathan-short** [segmentio/analytics.js#496]
When using analytics.js in Chrome for example, I can see in network debugger that events are sent to the server by POST - which lines up with expectations set by API doc: https://segment.com/docs/libraries/http/

When using IE9, I see in network debugger that it sends a GET, with a data param which is base64 encoded json payload.

I'm assuming this is a browser issue and not expected/desired behavior.

**Comment by hankim813** [comment]
Is this referring to the request sent to Segment (i.e https://api.segment.io/v1/p) or the requests going to your integrations' endpoints?

**Comment by f2prateek** [comment]
The requests to api.segment.io should use a POST.

* https://github.com/segment-integrations/analytics.js-integration-segmentio/blob/master/lib/index.js#L96
* https://github.com/segmentio/send-json/blob/master/lib/index.js#L64

Can you send us a screen recording if you're still seeing this issue? closing for now given how old this issue is and there wasn't a response to Han's question.
