### ISSUE TITLE
Adding 'new' Facebook pixel to analytics.js

### ISSUE THREAD

**Issue by albybarber** [segmentio/analytics.js#497]
Hi All,

Will you be integrating https://github.com/segment-integrations/analytics.js-integration-facebook-pixel into analytics.js?

Thanks.

**Comment by albybarber** [comment]
Any updates on the adding of this integration?

**Comment by drewbietron** [comment]
Plus one for support on this!

**Comment by hankim813** [comment]
[Facebook Pixel](https://segment.com/docs/integrations/facebook-pixel/) :)

**Comment by ndelage** [comment]
This is still an issue because of unsatisfied dependencies.

`analytics.js-integration-facebook-pixel` requires `analytics.js` ^2.11**.1**

But `analtyics.js` is currently at v2.11.**0**.  Check their respective `component.json` files.

It's a minor difference and I've hacked the two repos to work together, but unless you're up for some yak shaving this is a blocker for most people.

I'd wager that Segment customers use a version of `analtyics.js` that hasn't been made public.
