### ISSUE TITLE
Expose function for when integration loading is done (fail or pass)

### ISSUE THREAD

**Issue by tejasmanohar** [segmentio/analytics.js#500]
As @rawberg indicated [here](https://github.com/segmentio/analytics.js/issues/488#issue-110355267), it would be nice if there was a function like [`ready`](https://segment.com/docs/libraries/analytics.js/#ready) that fires when the integration load process is complete but not necessarily 100% successfully. Ideally, the callback function would have pass any errors, such as an integration load failure, as an argument.

**Comment by f2prateek** [comment]
The ready function can be called after initialization and it will invoke the callback immediately if integrations are already initialized.

The per integration callback will do the same https://github.com/segmentio/analytics.js-core/pull/33/files.

I don't think it's necessary to add a new API here?

Closing for now but let me know if you think strongly otherwise.
