### ISSUE TITLE
npm is out of date

### ISSUE THREAD

**Issue by brandly** [segmentio/analytics.js#505]
the [latest published version](https://www.npmjs.com/package/analytics.js) is `v2.9.1`

the repo lists `v2.11.0` as the [latest version](https://github.com/segmentio/analytics.js/blob/6bcd304eade35f74f9e89662120b4d3f1ad1ff0f/package.json#L4)

cc @yields since it looks like he did the releasing

thanks!

**Comment by tonyxiao** [comment]
@calvinfo fyi. Documentation on how to use `analytics.js` from npm is pretty sparse. We're also missing some clarification between `analytics.js` and `analytics-node` now that using npm on client-side is a much more common use-case.

**Comment by colllin** [comment]
`npm install segmentio/analytics.js#2.11.0 --save`

**Comment by joshgentry** [comment]
This is still an issue, and while there are workarounds, it's preferred to keep the NPM repository up to date so that package references for flexible versions (a la `^2.9.1`) will continue to receive updates.

**Comment by MPiccinato** [comment]
Anyone have an update on this?

**Comment by stefanmaric** [comment]
Did Segment stop publishing after TJ Holowaychuck stepped out?

Would love to see the npm package being maintained.

**Comment by f2prateek** [comment]
The recommended way of using analytics.js is from our CDN (https://segment.com/docs/sources/website/analytics.js/).

The NPM version is not currently being updated. We may pick this back up in the future, but I don't have an ETA for when that may be.

There's a limitation of the NPM version of analytics.js - you must load *every* integration, whether you use it or not. This worked fine when we had ~20-30 integrations, but we really started pushing it to it's limits with 80+ integrations. For reference, the CDN hosted version is able to support 143 client side integrations because it only loads the integrations you've enabled.

For these reasons, I'd recommend using the CDN hosted version if you can. If you can't, I'd recommend building from source using this repo as the starting point. building from source also lets you pick and choose only the integrations you need.
