### ISSUE TITLE
allow client code to set "messageId"

### ISSUE THREAD

**Issue by mnelson4** [segmentio/analytics.js#516]
I described an issue I'm having here: https://segment.forumbee.com/t/x18slj/can-you-add-a-unique-string-onto-api-calls-in-order-to-avoid-duplicates.
But the gist of it for analytics.js is this: can my client code explicitly tell analytics.js what "messageId" to set on messages sent to segment? Would that be an acceptable feature? 

(I think it would solve the problem I described on forumbee: when a server-side event happens, I'd set a messageId for it server-side too. That way, when it comes time to communicate that event to segment client-side, I know that even if the user somehow sends in multiple simultaneous requests, and the client-side js attempts to send that single real event to segment multiple times, segment will see they all have the same messageId, and so only use the first.)

**Comment by f2prateek** [comment]
It would technically be possible, but I'm not sure its the right solution for the problem. Partly because the messageId field is ignored by most client side integrations and they would still process the message twice.

The root of the problem seems to be:
> the page visited after the action is a redirection, we wait until we have a normal page where we can execute the segment.js before wiping the cookie data; this way we don't accidentally skip any track call

I think the correct fix within the library would be be to build some persistent queuing, either at the analytics.js level or the segment integration (the latter stills presents the problem for bundled client side integrations). This way you can safely make track calls during a redirect.

Otherwise there are a few solutions you can implement your end as well:

1. I think your current setup is reasonable (I would be surprised if it caused significant number of duplicates to cause any worry), and guarantees at least once delivery. And if this is a unique action for every user (i.e. happens only once for a single user, e.g. Signed Up), then you could dedupe in tools (e.g. SQL) using a unique `userId, event` combination.

2. Alternatively, you could either set a timeout after making the segment call and when the timeout completes, you can invoke the redirect (rather than invoking the redirect right away). This won't guarantee at least once delivery, but will improve your chances significantly. Even a 1 second timeout should increase your chances to >99.99%. And it will guarantee at most once delivery.

3. Lastly you can track the event on your server right when it processes the login or before redirecting. This will have close to perfect rate of delivery. I'd recommend tracking the event on the server if you need it to be ~100% reliable, given  the volatile nature of client side tracking. e.g. in your case the user could close the tab during redirect and never come back, and you'd lose the post redirect event. But if you tracked it server side, your server can ensure it gets delivered to Segment.

**Comment by mnelson4** [comment]
thanks for the reply @f2prateek!

> I think the correct fix within the library would be be to build some persistent queuing, either at the analytics.js level or the segment integration (the latter stills presents the problem for bundled client side integrations). This way you can safely make track calls during a redirect.

I don't exactly understand.

I want to double-check I'm clear about the current setup:

1. user submits a form that performs some action
2. in the server-side PHP code, we set a cookie so we remember what action was done. Then we sent a 302 HTTP response which redirects them to another page
3. while rendering the other page, the PHP sees the cookie that was set previously, and so echoes out the JS to the page for tracking the event
4. the JS sends the track message to segment/whatever else
5. once all those are done, we also sends a separate AJAX request to OUR server to request that the cookie be cleared. This way (we thought) there wouldnt send any more segment tracking requests

And so the problem we seem to sometimes have is that while step 4 is happening (we just sent the tracking request to segment in the JS, but have an AJAX request to our own server to clear the cookie) another page gets loaded (step 3 and then 4 again, but in a separate tab). 
So before the 1st page gets to step 5, which unsets the cookie, both pages have gone through step 4, sending the segment tracking requests.

So I've tried an implementation which swaps steps 4 and 5: so before we send segment tracking data, we clear the cookie which indicates we need to send tracking data. Also, we only send segment tracking data if the ajax request to ourselves successfully cleared the cookie; if the cookie was already cleared (by a previous ajax request), we then DON'T send the segment tracking data.

So far this modified approach seems to be working: no duplicate segment tracking requests being sent. And it doesn't need modifications to analytics.js, or gutting our current implementation and switching it to all server-side tracking
