### ISSUE TITLE
Distributed JS is bloated for no reason

### ISSUE THREAD

**Issue by pastelsky** [segmentio/analytics.js#519]
We currently use Segment with Google Analytics over here at my company.

The current size of analytics.min.js is **380KB** which apart from being a significant portion of our page weight, also has a large execution time on slower mobile devices. 

Building a custom version of analytics.js with GA integration gives a package of **just 104KB** which is  less than 1/3rd of the 380 KB. But we were wondering why segment's cdn doesn't do this automatically when we have only GA integration enabled in the segment dashboard.

There have been previous issues related to this — #314  , #351 but the official documentation still doesn't give any hints about loading only necessary integrations.

**Comment by hankim813** [comment]
@ndhoule

**Comment by jjshammas** [comment]
This is super vital for us to continue using Segment. It continues to trump the file size of our entire webpage! Would really like to see some sort of generator that spits out a file with only the desired integrations, or some sort of ES6/CommonJS module approach.

I'm fine with doing some grunt work to have to generate what I need—but right now it seems the only possibility is to sift through and filter 20,000 lines of code.

**Comment by f2prateek** [comment]
This is being worked on for the hosted version of analytics.js that is served by Segment. 

The initial challenge here was that analytics.js needs to be custom built with your project's specific set of integrations in realtime to handle requests, and running browserify was too slow to do this in realtime (in the order of seconds which is too slow for hTTP requests). We're trying out a new architecture to enable this.

I don't have an ETA, but we should be testing this out with in the upcoming months.

**Comment by f2prateek** [comment]
Being tracked internally at https://segment.atlassian.net/browse/PLATFORM-1661

**Comment by f2prateek** [comment]
Just to give an update, this has been incrementally rolling out for the past few weeks, and is expected to complete before the holidays.

**Comment by f2prateek** [comment]
This has been rolled out and you should see significantly smaller sizes going forwards. 

For a test Segment project with 1 client side integrations, here are the new sizes:

<img width="375" alt="screen shot 2018-12-12 at 7 40 59 pm" src="https://user-images.githubusercontent.com/843979/49914410-ff0c6100-fe45-11e8-8e8a-f99b2fc7286b.png">

Note that it's not quite the same as the open source version still because we support a few additional features in the segment hosted version, but we still have some further optimizations we'll be pursuing in the future.
