### ISSUE TITLE
Global namespace conflict between analytics.min.js and sjcl.min.js

### ISSUE THREAD

**Issue by caldwecr** [segmentio/analytics.js#525]
sjcl.min.js defines a globally namespaced function t

analytics.min.js defines a globally namespaced variable t (when this file fails to be loaded the conflict does not occur)

Because analytics.min.js is lazily loaded (and loaded last) it overwrites the function t

aws cognito identity sdk depends on sjcl.

Using the segment snippet stops a user from being able to authenticate with aws cognito user pool, using the js sdk.

See related issues

https://github.com/aws/amazon-cognito-identity-js/issues/197
https://github.com/bitwiseshiftleft/sjcl/issues/196

**Comment by WesleyDRobinson** [comment]
Looking at my personal analytics.min.js, it passes in `window.define` as `t` in the IIFE. I'm assuming this is to make the library [AMD compliant](http://javascriptplayground.com/blog/2012/10/making-your-library-amd-compliant/).
Lines 1,2 and 10814 from my personal analytics.min.js:formatted in Chrome DevTools:
```javascript
!function(t) {"function" == typeof t && t.amd && (t = void 0); 
  // analytics.js code
}(window.define);
```
Because `t` is scoped to the function, it should not conflict with the global namespace.
Try this example in the console:
```javascript
var t = 'global t';
!function (t) {
    console.log(t) // 'scoped t'
}('scoped t');
console.log(t); // 'global t'
```
Please provide a link that demonstrates the collision behavior, and I will investigate further.
