### ISSUE TITLE
Unwanted page track event on calling load twice

### ISSUE THREAD

**Issue by AdriVanHoudt** [segmentio/analytics.js#561]
We had a case where, due to a merge thingy, the `analytics.load` call happened twice.
This caused an unwanted page event to fire.

I know that you should not call load twice (I assume) but it should be a no op when it does.

**Comment by f2prateek** [comment]
Sorry for the delay. Don't think we're going to fix this, it's reasonable to expect load to not be called twice.

To confirm though, was this because you called load twice or or because you called page twice because you rendered this snippet twice https://segment.com/docs/sources/website/analytics.js/quickstart/#step-1-copy-the-snippet which includes a page call?

Don't think we can do anything for calling page twice.

Load also shouldn't be calling page internally anyways unless you enable the `initialPageView` setting (https://github.com/segmentio/analytics.js-core/blob/master/lib/analytics.js#L56), the segment hosted version doesn't use this setting. Of you'd like load to not send page calls, set this setting to false (which is the default).
