### ISSUE TITLE
Documentation: mention that Segment.io itself would need to be provided as an integration when .load's integrations are customized

### ISSUE THREAD

**Issue by jseppi** [segmentio/analytics.js#577]
https://segment.com/docs/sources/website/analytics.js/#load-options describes how integrations can be selectively enabled by specifying the `integrations` object in the call to `analytics.load`.

I think it would be nice to note that Segment.io itself needs to be specifically enabled when `All: false` is given. Perhaps the example could be changed from showing `'Google Analytics': true`:

<img width="814" alt="screen shot 2018-06-28 at 4 32 50 pm" src="https://user-images.githubusercontent.com/697848/42061816-033fb30e-7af1-11e8-8753-c53b419646fc.png">

to showing `'Segment.io': true`:

<img width="818" alt="screen shot 2018-06-28 at 4 33 09 pm" src="https://user-images.githubusercontent.com/697848/42061823-07170db0-7af1-11e8-8cc5-253635250b8b.png">

**Comment by f2prateek** [comment]
hey @jseppi - yep! will fix this. sorry for the delay here

**Comment by f2prateek** [comment]
Sorry forgot to post back here - but this should be updated now!

**Comment by nareshbhatia** [comment]
I tripped on this one too. In spite of the example showing `'Segment.io': true`, it is nowhere explicitly stated that you need it when `'All': false` is specified.

Also the first example under [Selecting Destinations](https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/#selecting-destinations) is wrong - it will not work as intended because `'Segment.io': true` is not specified.
