### ISSUE TITLE
False statement on segment.com documentation

### ISSUE THREAD

**Issue by e1himself** [segmentio/analytics.js#581]
On the segment.com documentation page (https://segment.com/docs/sources/website/analytics.js/) you claim that everyone can see what do you bundle within analytics.js script:

> All of our libraries are open source, and you can [view analytics.js on Github](https://github.com/segmentio/analytics.js).

But that's far from true. From what we see the open-sourced libraries are heavily outdated comparing to versions you serve. 

Is there a chance you'll start updating this package again (and others too)?

**Comment by f2prateek** [comment]
As mentioned in the [contributing section](https://github.com/segmentio/analytics.js#contributing
), Analytics.js is split up into multiple components - this repo itself is just a shell for them. 

https://github.com/segmentio/analytics.js-core is where the meat of the logic lives. The version on Github is what we are currently using in production. Are you seeing otherwise?

**Comment by e1himself** [comment]
Hm... Strange. 

From what I see there's a slightly different version of this code served. Thus I came to a conclusion it's using another repo.

# Served code

(a part of JS code cut)

```js
/*
 * Module dependencies.
 */

var analytics = require('@segment/analytics.js-core');
var each = require('@ndhoule/each');

/*
 * Exports.
 */

module.exports = function(Integrations) {
  each(function(Integration) {
    analytics.use(Integration);
  }, Integrations);

  return analytics;
};
```

# This repository code

```js
/**
 * Analytics.js
 *
 * (C) 2017 Segment Inc.
 */

var analytics = require('segmentio/analytics.js-core')
var Integrations = require('./integrations')
var each = require('each')

/**
 * Expose the `analytics` singleton.
 */

module.exports = exports = analytics

/**
 * Expose require.
 */

analytics.require = require

/**
 * Expose `VERSION`.
 */

exports.VERSION = require('../bower.json').version

/**
 * Add integrations.
 */

each(Integrations, function (name, Integration) {
  analytics.use(Integration)
});
```

**Comment by f2prateek** [comment]
This repo is the open source version which shows you how to wire the various components together, but it's not the final version we use because we need to wire them differently.

This is because the open source version doesn't require the concept of a Segment account. Because of this, we don't which integrations you may want to use, and provide every integration in the final package. This is wasteful, because it's unlikely that you are using a  mjoarity of these https://github.com/segmentio/analytics.js/blob/master/lib/integrations.js.

In the Segment hosted version we know which tools you have enabled so we dynamically fill in the list of tools you need to use and can shrink the size of the final a.js file we serve significantly.

**Comment by f2prateek** [comment]
But to clarify - we still use the open source versions of the different components that need to wired, e.g. analytics.js-core, analytics.js-integration and all the integrations themselves.

**Comment by e1himself** [comment]
Alright. That does make sense. Thanks @f2prateek :+1:
