### ISSUE TITLE
Building analytics.js with new monorepo?

### ISSUE THREAD

**Issue by dpolivy** [segmentio/analytics.js#615]
It looks like all of the analytics.js plugins have moved (back) to a [monorepo](https://github.com/segmentio/analytics.js-integrations), similar to how it was about 5 years ago.

However, this repo/build does not seem to use them, and is referencing the old individual plugin repos.

Are there plans to update this repo -- and the associated wiki documentation -- to use the current plugin repo?

I'm trying to update my old custom build of analytics.js, and am finding it frustrating to get it to work properly. Is the open source version here still being updated?

**Comment by dpolivy** [comment]
@f2prateek @ianstormtaylor

**Comment by pooyaj** [comment]
This version is no longer being updated. We recommend using either the CDN version, or if you like to go to npm route, then use [this example](https://github.com/segmentio/ajs-multiple-writekeys-demo) to import and use analytics library

**Comment by pooyaj** [comment]
@dpolivy the analytics.js in this repo is no longer maintained. If you like to build a custom version, here are the steps: 
- Import `analytics.js-core` as an npm package in your codebase. `analytics.js-core` is the base version that doesn't have any integrations. 
- Import integrations via npm and add [them individually ](https://github.com/segmentio/ajs-multiple-writekeys-demo/blob/master/src/App.js#L18) and initialize them with the correct settings.

**Comment by dpolivy** [comment]
@pooyaj Is there an automated build process that will package this up into a single minified file for client use, as the previous instructions provided?

**Comment by pooyaj** [comment]
@dpolivy we have an automated internal build system that packages `analytics.js-core`+ the integrations that a particular clients uses + all the user settings into a single personalized JS file and serves it over the CDN.

**Comment by dpolivy** [comment]
@pooyaj What about for people that don't use segment and just want to use the open source modules?

**Comment by pooyaj** [comment]
While the documentation around using open source modules can be improved, I think the best example is here: 
https://github.com/segmentio/ajs-multiple-writekeys-demo/blob/master/src/App.js#L17

Check out how the `greenAnalytics` and `blueAnalytics` are initialized. While this example adds a `Segment` integration, you can add [other integrations](https://github.com/segmentio/analytics.js-integrations/tree/master/integrations) instead of Segment, and use any of them without depending on Segment itself. Also re-iterating my previous comments, `analytics.js-core` package is agnostic to Segment as a service, and you can use it as an open source package with either integrations offered by Segment, or by creating and using your own integrations using this template.

**Comment by dpolivy** [comment]
Yes, I understand the part about how to use and initialize them. What I don't see in the sample (and I'm not familiar with React development, so maybe this is implicit in that) is how one generates a _built and minified_ `analytics.js` file containing just the integrations one wants. It'd be nice to have a sample for that scenario (which doesn't utilize react), similar to what used to exist a few iterations ago.

**Comment by pooyaj** [comment]
@dpolivy we just added react agnostic instructions here: https://github.com/segmentio/analytics.js-core#using-as-a-standalone-npm-package
