### ISSUE TITLE
Allow for IP masking

### ISSUE THREAD

**Issue by pablorecio** [segmentio/analytics.js#632]
While I understand [IPs can be anonymised](https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/#anonymizing-ip), it would be great for the library to also support partial masking like trimming the last octet from the address.

Any thoughts? Thanks!

**Comment by pooyaj** [comment]
Hey @pablorecio, the IP collection happens on the server side ( by the Segment backend ). Therefore, AJS library doesn't have access to the IP info (JS can't get access to user's IP address) to partially mask or modify part of the IP. The client side library can only override the IP info, so that the backend doesn't use the collected IP address.

**Comment by pablorecio** [comment]
@pooyaj sure, I understand that, but could't the backend accept a new parameter that will allow for said masking?
