### ISSUE TITLE
Last updated 2 years ago

### ISSUE THREAD

**Issue by balibebas** [segmentio/analytics.js#638]
It's rare to find web-based code that doesn't require more frequent maintenance. Today I became aware of https://github.com/davidwells/analytics which feels more extensible the way it's developed. So I'm curious what the future of this library looks like and if there are any plans to continue improving it.

**Comment by pooyaj** [comment]
@balibebas this repo is currently a placeholder for issues. Depending on your use case, we recommend using either: 
https://github.com/segmentio/analytics.js-core
or just the CDN version of the `analytics.js` served from 
`https://cdn.segment.com/analytics.js/v1/<WRITE_KEY>/analytics.js`

**Comment by balibebas** [comment]
Thanks things are becoming more clear now, Pooya. But I'm still confused. You said this repo is currently a placeholder for issues although it [contains a JavaScript file](https://github.com/segmentio/analytics.js/blob/master/analytics.js) with ~17K source lines of code and is seeing [5,000 downloads per week](https://openbase.io/js/analytics.js) on NPM. At what point do you decide to deprecate the NPM module?

**Comment by pooyaj** [comment]
@balibebas Fair point. This library is still functional, but outdated. Historically, this repo and its `npm` package was an alternative for those who wanted to use `analytics.js` as an open source module, rather than relying on the version served from our CDN. We packaged up two repos `analytics.js-core` and a subset of destinations ( currently in `analytics.js-integrations` ) and created a bundle: https://github.com/segmentio/analytics.js/blob/master/analytics.js that can be used as a standalone module. As you noted tho, this hasn't been updated for various reasons. One being that we now allow users to bundle `analytics.js-core` and their desired set of integrations themselves rather than relying on us to bundle it for them ( instructions [here](https://github.com/segmentio/analytics.js-core#using-as-a-standalone-npm-package) ). We can definitely do some house keeping on this repo, and mark `npm` package as deprecated or update the documentations. Currently we are focused on the improving our core libraries, and in near future will make a decision about this repo.
