### ISSUE TITLE
IE 8: `Version mismatch; please ensure you're using the latest version of the Mixpanel code snippet.`

### ISSUE THREAD

**Issue by pheuter** [segmentio/analytics.js#81]
When attempting to use Analytics.js with Mixpanel on IE 8, the following error is thrown:

_Version mismatch; please ensure you're using the latest version of the Mixpanel code snippet._

This does not occur on any other browser...

**Comment by nayaabkhan** [comment]
We have started getting this error again on IE8 today, did Mixpanel change something just recently? Because I think it was fine until last week and today we just saw this come up in our IE8 console.

Mix panel error:
Version mismatch; please ensure you're using the latest...
Object doesn't support property or method 'track_forms'
